### ISSUE TITLE
preventDuplicates?

### ISSUE THREAD

**Issue by 002** [scttcper/toastr-ng2#18]
On the demo you can check preventDuplicate, but when i put that option on the config i got the error that is not assignable to the toastr config.
So, is this option avaliable on v1.4.1?

**Comment by scttcper** [comment]
Only the demo was broken. It should be working now. Thanks

**Comment by 002** [comment]
i tested, still dont work for me, i dont know if im doing something wrong

`errorConfig: ToastrConfig;
ngOnInit(){
   this.errorConfig.preventDuplicates = true;
   this.toastrService.error('test','',this.errorConfig );
}
`

**Comment by scttcper** [comment]
Prevent duplicates is a global option.
https://github.com/scttcper/toastr-ng2#toastrconfig-global-options

**Comment by 002** [comment]
Thanks!
